
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: house_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  house-server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - C:\Users\NicoD\Desktop\temp:/usr/src/app/server/disk
    depends_on:
      - db

volumes:
  postgres_data: